# Generated by Django 5.2.3 on 2025-06-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "short_name",
                    models.CharField(max_length=255, verbose_name="Краткое имя"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "image_url",
                    models.CharField(max_length=255, verbose_name="URL картинки"),
                ),
                ("game_url", models.CharField(max_length=255, verbose_name="URL игры")),
                (
                    "short_description",
                    models.TextField(default="", verbose_name="Описание"),
                ),
                (
                    "long_description",
                    models.TextField(default="", verbose_name="Полное описание"),
                ),
                ("year", models.IntegerField(default=0, verbose_name="Год")),
                (
                    "developer",
                    models.CharField(
                        default="", max_length=255, verbose_name="Разработчик"
                    ),
                ),
                (
                    "version",
                    models.CharField(default="", max_length=255, verbose_name="Версия"),
                ),
                (
                    "language",
                    models.CharField(default="", max_length=255, verbose_name="Язык"),
                ),
                ("tablet", models.BooleanField(default=False, verbose_name="Таблетка")),
                (
                    "genre",
                    models.CharField(default="", max_length=255, verbose_name="Жанр"),
                ),
                (
                    "os",
                    models.CharField(
                        default="", max_length=255, verbose_name="Операционная система"
                    ),
                ),
                (
                    "cpu",
                    models.CharField(
                        default="", max_length=255, verbose_name="Процессор"
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        default="", max_length=255, verbose_name="Оперативная память"
                    ),
                ),
                (
                    "gpu",
                    models.CharField(
                        default="", max_length=255, verbose_name="Видео карты"
                    ),
                ),
                (
                    "size",
                    models.CharField(default="", max_length=255, verbose_name="Размер"),
                ),
                (
                    "additional_info",
                    models.TextField(
                        default="", verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "pic1_url",
                    models.CharField(
                        default="", max_length=255, verbose_name="URL картинки 1"
                    ),
                ),
                (
                    "pic2_url",
                    models.CharField(
                        default="", max_length=255, verbose_name="URL картинки 2"
                    ),
                ),
                (
                    "pic3_url",
                    models.CharField(
                        default="", max_length=255, verbose_name="URL картинки 3"
                    ),
                ),
                (
                    "download_url1",
                    models.CharField(
                        default="",
                        max_length=255,
                        verbose_name="Ссылка на скачивание 1",
                    ),
                ),
                (
                    "download_url2",
                    models.CharField(
                        default="",
                        max_length=255,
                        verbose_name="Ссылка на скачивание 2",
                    ),
                ),
                (
                    "download_url3",
                    models.CharField(
                        default="",
                        max_length=255,
                        verbose_name="Ссылка на скачивание 3",
                    ),
                ),
                (
                    "download_url4",
                    models.CharField(
                        default="",
                        max_length=255,
                        verbose_name="Ссылка на скачивание 4",
                    ),
                ),
                (
                    "download_url5",
                    models.CharField(
                        default="",
                        max_length=255,
                        verbose_name="Ссылка на скачивание 5",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        to="games.category", verbose_name="Категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Игра",
                "verbose_name_plural": "Игры",
            },
        ),
    ]
