# Generated by Django 5.2.3 on 2025-06-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="tablet",
            field=models.CharField(default="", max_length=255, verbose_name="Таблетка"),
        ),
    ]
