# Generated by Django 5.2.3 on 2025-06-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_game_tablet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("text", models.TextField(max_length=2048, verbose_name="Текст")),
                (
                    "on_moderation",
                    models.BooleanField(default=False, verbose_name="На модерации"),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AddField(
            model_name="game",
            name="comments",
            field=models.ManyToManyField(
                to="games.comment", verbose_name="Комментарии"
            ),
        ),
    ]
