# Generated by Django 5.2.3 on 2025-06-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_comment_game_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="year",
            field=models.CharField(default=0, verbose_name="Год"),
        ),
    ]
