# Generated by Django 5.2.3 on 2025-06-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_alter_game_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="dislikes",
            field=models.IntegerField(default=0, verbose_name="Дизлайки"),
        ),
        migrations.AddField(
            model_name="game",
            name="downloaded_count",
            field=models.IntegerField(default=0, verbose_name="Количество скачиваний"),
        ),
        migrations.AddField(
            model_name="game",
            name="likes",
            field=models.IntegerField(default=0, verbose_name="Лайки"),
        ),
    ]
