# Generated by Django 5.2.3 on 2025-06-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_game_dislikes_game_downloaded_count_game_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, max_length=2048, null=True, verbose_name="Текст"
            ),
        ),
    ]
